### Create Report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Hyundai",
    "model": "Sonata",
    "year": 2018,
    "price": 10000,
    "mileage": 50000,
    "lng": -122.084,
    "lat": 37.422
}

### Approve Report
PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
    "approved": false
}

### Get Report
GET http://localhost:3000/reports?make=toyota&model=corolla&year=2015&price=10000&mileage=50000&lng=-122.084&lat=37.422
