### User signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test12@gmail.com",
    "password": "123456"
}

### User Sigin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test12@gmail.com",
    "password": "123456"
}

### User Signout
POST http://localhost:3000/auth/signout

### whoami
GET http://localhost:3000/auth/whoami
Cookie: session=eyJ1c2VySWQiOjh9; path=/; httponly,session.sig=ARk1L1K7HUyuVyJ_B3hWdZIx7Ac; path=/; httponly
### User Fetch
GET http://localhost:3000/auth/10

### Query User
GET http://localhost:3000/auth?email=test10@gmail.com

### Delete User
DELETE http://localhost:3000/auth/2

### Update User
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "test2@gmail.com"
}